
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  creationTimestamp: null
  name: manager-role
rules:
- apiGroups:
  - groupa.k8s.demo.com
  resources:
  - apiexampleas
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - groupa.k8s.demo.com
  resources:
  - apiexampleas/finalizers
  verbs:
  - update
- apiGroups:
  - groupa.k8s.demo.com
  resources:
  - apiexampleas/status
  verbs:
  - get
  - patch
  - update
